# Generated by Django 4.2.16 on 2026-06-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('exam_type', models.CharField(choices=[('ielts', 'IELTS'), ('cefr', 'CEFR'), ('national', 'Milliy Sertifikat'), ('dtm', 'DTM'), ('ielts_academic', 'IELTS Academic'), ('ielts_general', 'IELTS General Training')], max_length=30, unique=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='exams/')),
                ('color', models.CharField(default='#4F46E5', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('total_sections', models.IntegerField(default=0)),
                ('passing_score', models.CharField(blank=True, max_length=50)),
                ('validity_years', models.IntegerField(default=2)),
                ('fee_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('official_website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Imtihon turi',
                'verbose_name_plural': 'Imtihon turlari',
            },
        ),
        migrations.CreateModel(
            name='IELTSTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('general', 'Umumiy')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'IELTS maslahat',
                'verbose_name_plural': 'IELTS maslahatlar',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficiency'), ('4.0', 'IELTS 4.0'), ('4.5', 'IELTS 4.5'), ('5.0', 'IELTS 5.0'), ('5.5', 'IELTS 5.5'), ('6.0', 'IELTS 6.0'), ('6.5', 'IELTS 6.5'), ('7.0', 'IELTS 7.0'), ('7.5', 'IELTS 7.5'), ('8.0', 'IELTS 8.0')], max_length=10)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('total_questions', models.IntegerField(default=40)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exams', to='exams.examtype')),
            ],
            options={
                'verbose_name': 'Mock imtihon',
                'verbose_name_plural': 'Mock imtihonlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section_type', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('mixed', 'Aralash')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('max_score', models.IntegerField(default=9)),
                ('order', models.IntegerField(default=0)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.examtype')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NationalCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('duration_minutes', models.IntegerField(default=90)),
                ('total_questions', models.IntegerField(default=50)),
                ('passing_percentage', models.IntegerField(default=70)),
                ('is_active', models.BooleanField(default=True)),
                ('fee_uzs', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_certs', to='courses.subject')),
            ],
            options={
                'verbose_name': 'Milliy sertifikat',
                'verbose_name_plural': 'Milliy sertifikatlar',
                'unique_together': {('subject', 'level')},
            },
        ),
    ]
