# Generated by Django 4.2.16 on 2026-06-07 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text="Telegram chat/user ID — bot orqali bog'langan", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=48, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram ulash token',
                'verbose_name_plural': 'Telegram ulash tokenlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
