# Generated by Django 4.2.16 on 2026-06-15 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file_id', models.CharField(help_text='Telegram file_id (rasm)', max_length=300)),
                ('user_chat_id', models.BigIntegerField(help_text='Foydalanuvchining Telegram chat ID')),
                ('admin_msg_id', models.IntegerField(blank=True, help_text='Admin chatdagi xabar ID', null=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Admin izohi (rad etilsa sababi)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "To'lov cheki",
                'verbose_name_plural': "To'lov cheklari",
                'ordering': ['-created_at'],
            },
        ),
    ]
