# Generated by Django 4.2.16 on 2026-06-05 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'OTP kod',
                'verbose_name_plural': 'OTP kodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('uzcard', 'UzCard'), ('humo', 'Humo'), ('stripe', 'Stripe (Visa/MC)'), ('cash', 'Naqd')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('completed', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz'), ('cancelled', 'Bekor qilingan'), ('refunded', 'Qaytarilgan')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('provider_transaction_id', models.CharField(blank=True, help_text='Payme/Click tomonidan berilgan ID', max_length=200)),
                ('provider_data', models.JSONField(blank=True, default=dict, help_text="To'lov tizimidan kelgan to'liq ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('free', 'Bepul'), ('monthly', 'Oylik'), ('quarterly', '3 oylik'), ('annual', 'Yillik')], max_length=20, unique=True)),
                ('price_uzs', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('duration_days', models.IntegerField(default=30)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(default=list)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_percent', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Obuna reja',
                'verbose_name_plural': 'Obuna rejalar',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan'), ('pending', 'Kutilmoqda')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payme_id', models.CharField(help_text='Payme tomonidan berilgan _id', max_length=255, unique=True)),
                ('state', models.IntegerField(default=1)),
                ('amount', models.BigIntegerField(help_text='Tiyin da')),
                ('created_time', models.BigIntegerField(blank=True, null=True)),
                ('perform_time', models.BigIntegerField(blank=True, default=0, null=True)),
                ('cancel_time', models.BigIntegerField(blank=True, default=0, null=True)),
                ('reason', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payme_transaction', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payme tranzaksiya',
                'verbose_name_plural': 'Payme tranzaksiyalar',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.subscription'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClickTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_trans_id', models.CharField(db_index=True, max_length=255)),
                ('service_id', models.CharField(max_length=100)),
                ('click_paydoc_id', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('action', models.IntegerField()),
                ('error_code', models.IntegerField(default=0)),
                ('sign_time', models.CharField(max_length=100)),
                ('sign_string', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_transactions', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Click tranzaksiya',
                'verbose_name_plural': 'Click tranzaksiyalar',
            },
        ),
    ]
