# Generated by Django 4.2.16 on 2026-06-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTMDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('technical', 'Texnika va texnologiya'), ('natural', 'Tabiiy fanlar'), ('medical', 'Tibbiyot'), ('economic', 'Ijtimoiy-iqtisodiy'), ('humanitarian', 'Gumanitar'), ('pedagogical', 'Pedagogika'), ('law', 'Huquq'), ('agriculture', "Qishloq xo'jaligi"), ('art', "San'at va madaniyat"), ('sports', 'Jismoniy tarbiya'), ('military', 'Harbiy')], max_length=30)),
                ('university_type', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('grant_places', models.IntegerField(default=0)),
                ('contract_places', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "DTM Yo'nalish",
                'verbose_name_plural': "DTM Yo'nalishlar",
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DTMSubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='dtm.dtmdirection')),
                ('first_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_for_groups', to='courses.subject', verbose_name='1-fan')),
                ('mandatory_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatory_for_groups', to='courses.subject', verbose_name="Majburiy fan (o'zbek tili va matematika)")),
                ('second_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_for_groups', to='courses.subject', verbose_name='2-fan')),
            ],
            options={
                'verbose_name': 'DTM Fan guruhi',
                'verbose_name_plural': 'DTM Fan guruhlari',
            },
        ),
        migrations.CreateModel(
            name='DTMPastYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('grant_score', models.FloatField(blank=True, help_text='Grant ball chegarasi', null=True)),
                ('contract_score', models.FloatField(blank=True, help_text='Kontrakt ball chegarasi', null=True)),
                ('total_applicants', models.IntegerField(default=0)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_years', to='dtm.dtmdirection')),
            ],
            options={
                'verbose_name': "O'tgan yil ma'lumoti",
                'verbose_name_plural': "O'tgan yillar ma'lumotlari",
                'ordering': ['-year'],
                'unique_together': {('direction', 'year')},
            },
        ),
    ]
